name: wallet
description: "AfricRemit Accessment project"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  webview_flutter: ^4.13.1
  http: ^1.6.0
  flutter_riverpod: ^2.4.0
  google_fonts: ^8.0.1
  equatable: ^2.0.8
  shared_preferences: ^2.5.4
  dotted_border: ^3.1.0
  bot_toast: ^4.1.3
  loading_progress_indicator: ^0.1.6
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
